import { useMemo, useState } from 'react';
import type { FormEvent } from 'react';
import { BrowserRouter, Link, Navigate, Route, Routes, useLocation, useNavigate } from 'react-router-dom';
import { Activity, BarChart3, Boxes, CheckCircle2, ClipboardList, Home, LifeBuoy, Plus, Settings, ShieldCheck, Sparkles, Users } from 'lucide-react';
import { AppShell } from '../template/AppShell';
import { RouteGuard, assumeDemoRole, demoAuthAdapter } from '../template/auth';
import { TemplateProvider, useTemplate } from '../template/context';
import type { NavItem, Role } from '../template/types';
import { Alert, Badge, Button, Card, DataTable, EmptyState, ErrorState, Input, Modal, PageHeader, ProgressBar, Select, StatCard, Textarea, Tile } from '../template/ui';
import { messages } from './messages';

const brand = { name: 'Iris', shortName: 'I', tagline: 'A flexible foundation for modern products', logo: <span className="shell-brand__mark">I</span> };

function DemoRoutes() {
  const { t } = useTemplate();
  const navigation: NavItem[] = [
    { id: 'home', label: t('navHome'), to: '/', icon: Home, mobile: true },
    { id: 'workspace', label: t('navWorkspace'), to: '/workspace', icon: ClipboardList, authenticated: true, mobile: true },
    { id: 'components', label: t('navComponents'), to: '/components', icon: Boxes, mobile: true },
    { id: 'support', label: t('navSupport'), to: '/support', icon: LifeBuoy, authenticated: true, mobile: true },
    { id: 'admin', label: t('navAdmin'), to: '/admin', icon: Settings, authenticated: true, minimumRole: 'admin', mobile: true },
    { id: 'users', label: t('navUsers'), to: '/admin/users', icon: Users, authenticated: true, minimumRole: 'superadmin', mobile: false },
  ];
  return <Routes><Route element={<AppShell brand={brand} navigation={navigation} announcements={<DemoAnnouncement />} />}>
    <Route index element={<HomePage />} /><Route path="login" element={<LoginPage />} /><Route path="register" element={<RegisterPage />} /><Route path="components" element={<ComponentsPage />} />
    <Route element={<RouteGuard />}><Route path="workspace" element={<WorkspacePage />} /><Route path="support" element={<SupportPage />} /></Route>
    <Route element={<RouteGuard minimumRole="admin" />}><Route path="admin" element={<AdminPage />} /></Route>
    <Route element={<RouteGuard minimumRole="superadmin" />}><Route path="admin/users" element={<UsersPage />} /></Route>
    <Route path="forbidden" element={<StatusPage code="403" title="Access denied" detail="Your account does not have permission to view this page." />} />
    <Route path="*" element={<StatusPage code="404" title="Page not found" detail="The page may have moved or no longer exists." />} />
  </Route></Routes>;
}

export default function DemoApp() {
  return <TemplateProvider authAdapter={demoAuthAdapter} messages={messages} defaultLocale="en" defaultTheme="obsidian" onAssumeRole={assumeDemoRole}><BrowserRouter><DemoRoutes /></BrowserRouter></TemplateProvider>;
}

function DemoAnnouncement() { const [visible, setVisible] = useState(true); if (!visible) return null; return <div className="demo-announcement"><Sparkles size={16} /><span>This is a fully interactive template. Switch themes, languages and roles to explore it.</span><button onClick={() => setVisible(false)}>Dismiss</button></div>; }

function HomePage() {
  const { session, t } = useTemplate();
  return <div className="page page--wide"><section className="demo-hero"><div><Badge variant="info">Application template</Badge><h1>{session ? t('welcome', { name: session.user.displayName }) : 'Build products on a proven foundation.'}</h1><p>{session ? t('overview') : 'Responsive layouts, role-aware navigation, authentication, i18n, themes and production-ready components—without product-specific assumptions.'}</p><div className="ui-actions">{session ? <Button icon={<ClipboardList size={17} />} onClick={() => location.assign('/workspace')}>Open workspace</Button> : <Link to="/login"><Button>Explore the demo</Button></Link>}<Link to="/components"><Button variant="outline">View components</Button></Link></div></div><Card className="demo-hero__panel"><div className="demo-signal"><span /><small>System operational</small></div><BarChart3 size={80} /><strong>74%</strong><p>Quarterly objective progress</p><ProgressBar value={74} /></Card></section><section className="ui-grid ui-grid--3"><Tile icon={<Activity />} eyebrow="Observe" title="Operational overview" description="Reusable status, metric and progress components." /><Tile icon={<ShieldCheck />} eyebrow="Control" title="Role-aware access" description="User, administrator and super-administrator routes." /><Tile icon={<Boxes />} eyebrow="Extend" title="Composable building blocks" description="Swap your domain data into neutral components." /></section></div>;
}

function LoginPage() {
  const { session, login, assumeRole } = useTemplate(); const navigate = useNavigate(); const location = useLocation(); const [email, setEmail] = useState('user@example.test'); const [password, setPassword] = useState('demopassword'); const [error, setError] = useState(''); const [busy, setBusy] = useState(false);
  const submit = async (event: FormEvent) => { event.preventDefault(); setBusy(true); setError(''); try { await login({ email, password }); const target = (location.state as { from?: { pathname?: string } } | null)?.from?.pathname ?? '/workspace'; navigate(target, { replace: true }); } catch (reason) { setError(reason instanceof Error ? reason.message : 'Unable to sign in.'); } finally { setBusy(false); } };
  if (session) return <Navigate to="/workspace" replace />;
  return <AuthPanel title="Welcome back" description="Sign in with any email. Prefix it with admin or super to test elevated roles."><form className="ui-form" onSubmit={submit}><Input label="Email" type="email" value={email} onChange={(e) => setEmail(e.target.value)} autoComplete="email" required /><Input label="Password" type="password" value={password} onChange={(e) => setPassword(e.target.value)} autoComplete="current-password" required />{error && <Alert variant="danger">{error}</Alert>}<Button type="submit" loading={busy}>Sign in</Button></form><div className="demo-role-switch"><span>Quick role demo</span>{(['user', 'admin', 'superadmin'] as Role[]).map((role) => <Button key={role} size="sm" variant="secondary" onClick={() => { assumeRole?.(role); navigate(role === 'superadmin' ? '/admin/users' : role === 'admin' ? '/admin' : '/workspace'); }}>{role}</Button>)}</div><p className="ui-centered ui-muted">New here? <Link to="/register">Create an account</Link></p></AuthPanel>;
}

function RegisterPage() {
  const { register } = useTemplate(); const navigate = useNavigate(); const [form, setForm] = useState({ displayName: '', email: '', password: '', confirm: '' }); const [error, setError] = useState(''); const [busy, setBusy] = useState(false);
  const submit = async (event: FormEvent) => { event.preventDefault(); if (form.password !== form.confirm) { setError('Passwords do not match.'); return; } setBusy(true); setError(''); try { await register(form); navigate('/workspace'); } catch (reason) { setError(reason instanceof Error ? reason.message : 'Unable to create account.'); } finally { setBusy(false); } };
  return <AuthPanel title="Create your account" description="The adapter can be replaced with your own API implementation."><form className="ui-form" onSubmit={submit}><Input label="Display name" value={form.displayName} onChange={(e) => setForm({ ...form, displayName: e.target.value })} required /><Input label="Email" type="email" value={form.email} onChange={(e) => setForm({ ...form, email: e.target.value })} required /><Input label="Password" type="password" minLength={8} value={form.password} onChange={(e) => setForm({ ...form, password: e.target.value })} required /><Input label="Confirm password" type="password" value={form.confirm} onChange={(e) => setForm({ ...form, confirm: e.target.value })} required />{error && <Alert variant="danger">{error}</Alert>}<Button type="submit" loading={busy}>Create account</Button></form><p className="ui-centered ui-muted">Already registered? <Link to="/login">Sign in</Link></p></AuthPanel>;
}

function AuthPanel({ title, description, children }: { title: string; description: string; children: React.ReactNode }) { return <div className="page auth-page"><Card className="auth-card"><div className="auth-card__heading"><span className="shell-brand__mark">I</span><h1>{title}</h1><p>{description}</p></div>{children}</Card></div>; }

const workItems = [
  { id: 'WK-1042', title: 'Quarterly planning', owner: 'M. Chen', status: 'Active', due: 'Oct 8' },
  { id: 'WK-1038', title: 'Customer onboarding', owner: 'A. Jensen', status: 'Review', due: 'Oct 10' },
  { id: 'WK-1029', title: 'Policy refresh', owner: 'S. Novak', status: 'Draft', due: 'Oct 17' },
];
function WorkspacePage() { const { session } = useTemplate(); return <div className="page page--wide"><PageHeader eyebrow="Workspace" title={`Good morning, ${session?.user.displayName}`} description="A responsive dashboard assembled from template components." actions={<Button icon={<Plus size={16} />}>New item</Button>} /><div className="ui-grid ui-grid--4"><StatCard label="Active items" value="24" change="+8% this month" icon={<ClipboardList />} /><StatCard label="Completion" value="86%" change="+4.2%" icon={<CheckCircle2 />} /><StatCard label="Team members" value="12" icon={<Users />} /><StatCard label="Open alerts" value="3" icon={<Activity />} /></div><Card className="section-card"><div className="section-heading"><div><h2>Recent work</h2><p className="ui-muted">Items updated across your organization</p></div><Button variant="ghost">View all</Button></div><DataTable rows={workItems} columns={[{ key: 'id', label: 'ID' }, { key: 'title', label: 'Title' }, { key: 'owner', label: 'Owner' }, { key: 'status', label: 'Status', render: (row) => <Badge variant={row.status === 'Active' ? 'success' : row.status === 'Review' ? 'warning' : 'neutral'}>{String(row.status)}</Badge> }, { key: 'due', label: 'Due' }]} /></Card></div>; }

function ComponentsPage() { const [modal, setModal] = useState(false); return <div className="page page--wide"><PageHeader eyebrow="Design system" title="Reusable components" description="A compact selection of the generalized primitives included in the template." /><Card className="section-card"><h2>Actions and badges</h2><div className="ui-component-row"><Button>Primary</Button><Button variant="secondary">Secondary</Button><Button variant="outline">Outline</Button><Button variant="danger">Danger</Button><Button variant="ghost" loading>Working</Button></div><div className="ui-component-row"><Badge>Neutral</Badge><Badge variant="info">Information</Badge><Badge variant="success" pulse>Active</Badge><Badge variant="warning">Warning</Badge><Badge variant="danger">Error</Badge><Badge variant="admin">Admin</Badge><Badge variant="superadmin">Superadmin</Badge></div></Card><div className="ui-grid ui-grid--2"><Card className="section-card"><h2>Form fields</h2><div className="ui-form"><Input label="Project name" placeholder="Example project" hint="Use a clear, recognizable name." /><Select label="Category" defaultValue="operations"><option value="operations">Operations</option><option value="people">People</option></Select><Textarea label="Description" placeholder="Add context…" /><Button onClick={() => setModal(true)}>Open modal</Button></div></Card><Card className="section-card"><h2>Data states</h2><Alert variant="success" title="Saved">Your changes are now available.</Alert><ProgressBar value={68} label="Migration progress" /><EmptyState title="No archived items" description="Archived records will appear here." action={<Button size="sm" variant="outline">Create item</Button>} /><ErrorState error="The example service could not be reached." onRetry={() => undefined} /></Card></div><Modal open={modal} onClose={() => setModal(false)} title="Confirm action" footer={<div className="ui-actions"><Button variant="secondary" onClick={() => setModal(false)}>Cancel</Button><Button onClick={() => setModal(false)}>Confirm</Button></div>}><p>This accessible modal closes from its button, backdrop or the Escape key.</p></Modal></div>; }

function SupportPage() { const [sent, setSent] = useState(false); const submit = (event: FormEvent) => { event.preventDefault(); setSent(true); }; return <div className="page page--narrow"><PageHeader eyebrow="Support" title="How can we help?" description="This generalized contact form can submit to your own support adapter or API." />{sent ? <Alert variant="success" title="Message received">We will get back to you shortly.</Alert> : <Card className="section-card"><form className="ui-form" onSubmit={submit}><div className="ui-grid ui-grid--2"><Input label="Name" required /><Input label="Email" type="email" required /></div><Select label="Topic"><option>General question</option><option>Technical issue</option><option>Account and access</option></Select><Input label="Subject" required /><Textarea label="Message" rows={6} required /><Button type="submit">Send message</Button></form></Card>}</div>; }

function AdminPage() { const [notice, setNotice] = useState(true); return <div className="page page--wide"><PageHeader eyebrow="Administration" title="Operations dashboard" description="Configuration, activity and content management for administrators." actions={<Link to="/admin/users"><Button variant="outline" icon={<Users size={16} />}>User management</Button></Link>} />{notice && <Alert variant="warning" title="Review requested" onDismiss={() => setNotice(false)}>Two changes require administrator approval.</Alert>}<div className="ui-grid ui-grid--3"><Tile icon={<Settings />} title="Configuration" description="Manage organization-level defaults and feature controls." action={<Button size="sm" variant="ghost">Manage</Button>} badge={<Badge variant="success">Healthy</Badge>} /><Tile icon={<ClipboardList />} title="Content" description="Create, publish, archive and audit domain records." action={<Button size="sm" variant="ghost">Open</Button>} badge={<Badge variant="warning">2 drafts</Badge>} /><Tile icon={<BarChart3 />} title="Reporting" description="Monitor adoption and operational trends." action={<Button size="sm" variant="ghost">View</Button>} /></div></div>; }

function UsersPage() { const [query, setQuery] = useState(''); const rows = useMemo(() => [{ id: 'U-1001', name: 'Alex Morgan', email: 'alex@example.test', role: 'user' }, { id: 'U-1002', name: 'Robin Singh', email: 'robin@example.test', role: 'admin' }, { id: 'U-1003', name: 'Taylor Kim', email: 'taylor@example.test', role: 'superadmin' }].filter((row) => `${row.name} ${row.email}`.toLowerCase().includes(query.toLowerCase())), [query]); return <div className="page page--wide"><PageHeader eyebrow="Super administration" title="User management" description="Search accounts, inspect access and assign roles." actions={<Button icon={<Plus size={16} />}>Add administrator</Button>} /><Card className="section-card"><Input aria-label="Search users" placeholder="Search by name or email…" value={query} onChange={(e) => setQuery(e.target.value)} /><DataTable rows={rows} empty={<EmptyState title="No matching users" description="Try a different search term." />} columns={[{ key: 'name', label: 'Name' }, { key: 'email', label: 'Email' }, { key: 'role', label: 'Role', render: (row) => <Badge variant={row.role === 'superadmin' ? 'superadmin' : row.role === 'admin' ? 'admin' : 'neutral'}>{String(row.role)}</Badge> }, { key: 'actions', label: 'Actions', render: () => <Button size="sm" variant="ghost">Edit</Button> }]} /></Card></div>; }

function StatusPage({ code, title, detail }: { code: string; title: string; detail: string }) { return <div className="page status-page"><strong>{code}</strong><h1>{title}</h1><p>{detail}</p><Link to="/"><Button variant="outline">Return home</Button></Link></div>; }
